# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4b4431377a74a7c11e575810a1b927461345f962e0fe41159a0e1c1a4babeec486ddb655e1f95cb0eb49a03c2b96ea7eea5ce7724d6e6320f12dff7e607baae

test:
  secret_key_base: 94537e8875eb3e870e355b674feaae9b4bb999f2ca1f7761d0b7e423e9e47f3bfc72bc00e8770ba5bfbdc413c052741c0027bb7aa3f52f3cbbf974b140077625

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
